name: CI/CD Docker

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag Release (v1.0.0, v1.0.1, etc)'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t testing/welcome:latest .
          docker tag testing/welcome:latest testing/welcome:${{ github.event.inputs.release_tag }}

      - name: Push Docker Image
        run: |
          docker push testing/welcome:latest
          docker push testing/welcome:${{ github.event.inputs.release_tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no user-server@fqdn-or-ip-server "docker pull testing/welcome:latest && docker stop app || true && docker rm app || true && docker run -d --name app -p 8000:5000 testing/welcome:latest"
